load_lib(LIB_PATH "libg2o_stuff.so" );
load_lib(LIB_PATH "libg2o_core.so" );
load_lib(LIB_PATH "libg2o_ext_csparse.so" );
load_lib(LIB_PATH "libg2o_csparse_extension.so" );
load_lib(LIB_PATH "libg2o_solver_csparse.so" );
load_lib(LIB_PATH "libg2o_types_slam3d.so" );
load_lib(LIB_PATH "libg2o_types_sba.so" );
load_lib(LIB_PATH "libg2o_types_sim3.so" );
load_lib(LIB_PATH "libpangolin.so" );
